### ISSUE TITLE
Can't build - Python issue on "db" container

### ISSUE THREAD

**Issue by remialvado** [mattermost/mattermost-docker#53]
Hi, 

I've got an error when trying to exec `docker-compose build` after cloning the repository. The error looks like this : 

```
remi@ns3151751:~/mattermost/mattermost-docker$ git status
HEAD détachée sur 3.4.0
rien à valider, la copie de travail est propre
remi@ns3151751:~/mattermost/mattermost-docker$ docker-compose build
Building db
Step 1 : FROM postgres:9.4
9.4: Pulling from library/postgres
6a5a5368e0c2: Pull complete
193f770cec44: Pull complete
33647077f2ee: Pull complete
53bc65f84840: Pull complete
a4d3b0f1c16a: Pull complete
bdbe3c2ddbbd: Pull complete
6ce1015b914c: Pull complete
19631bdff29c: Pull complete
66adf788dd4c: Pull complete
79dc48693081: Pull complete
6121a13ba57c: Pull complete
Digest: sha256:9149f6309b83c9b99ae2e1ecab3e14a9662a1a8d0159320c24e34827ffe4c930
Status: Downloaded newer image for postgres:9.4
 ---> cd870518bdf0
Step 2 : RUN apt-get update     && apt-get install -y python-dev lzop pv daemontools curl build-essential     && curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | python     && pip install wal-e     && apt-get remove -y build-essential python-dev     && apt-get autoremove -y     && apt-get clean     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Running in fa6cf07e86ba
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 http://apt.postgresql.org jessie-pgdg InRelease [46.7 kB]
Ign http://httpredir.debian.org jessie InRelease
Get:3 http://httpredir.debian.org jessie-updates InRelease [142 kB]
Get:4 http://security.debian.org jessie/updates/main amd64 Packages [391 kB]
Get:5 http://httpredir.debian.org jessie Release.gpg [2,373 B]
Get:6 http://httpredir.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:7 http://httpredir.debian.org jessie Release [148 kB]
Get:8 http://apt.postgresql.org jessie-pgdg/main amd64 Packages [106 kB]
Get:9 http://httpredir.debian.org jessie/main amd64 Packages [9,064 kB]
Get:10 http://apt.postgresql.org jessie-pgdg/9.4 amd64 Packages [1,708 B]
Fetched 9,983 kB in 3s (2,862 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  binutils ca-certificates cpp cpp-4.9 dpkg-dev fakeroot g++ g++-4.9 gcc
  gcc-4.9 libalgorithm-diff-perl libalgorithm-diff-xs-perl
  libalgorithm-merge-perl libasan1 libatomic1 libc-dev-bin libc6-dev
  libcilkrts5 libcloog-isl4 libcurl3 libdpkg-perl libexpat1-dev libfakeroot
  libfile-fcntllock-perl libgcc-4.9-dev libgomp1 libidn11 libisl10 libitm1
  liblsan0 liblzo2-2 libmpc3 libmpfr4 libpython-dev libpython2.7
  libpython2.7-dev libquadmath0 librtmp1 libssh2-1 libstdc++-4.9-dev
  libtimedate-perl libtsan0 libubsan0 linux-libc-dev make manpages
  manpages-dev patch python2.7-dev xz-utils
Suggested packages:
  binutils-doc cpp-doc gcc-4.9-locales daemontools-run runit debian-keyring
  g++-multilib g++-4.9-multilib gcc-4.9-doc libstdc++6-4.9-dbg gcc-multilib
  autoconf automake libtool flex bison gdb gcc-doc gcc-4.9-multilib
  libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan1-dbg
  liblsan0-dbg libtsan0-dbg libubsan0-dbg libcilkrts5-dbg libquadmath0-dbg
  glibc-doc libstdc++-4.9-doc make-doc man-browser ed diffutils-doc doc-base
The following NEW packages will be installed:
  binutils build-essential ca-certificates cpp cpp-4.9 curl daemontools
  dpkg-dev fakeroot g++ g++-4.9 gcc gcc-4.9 libalgorithm-diff-perl
  libalgorithm-diff-xs-perl libalgorithm-merge-perl libasan1 libatomic1
  libc-dev-bin libc6-dev libcilkrts5 libcloog-isl4 libcurl3 libdpkg-perl
  libexpat1-dev libfakeroot libfile-fcntllock-perl libgcc-4.9-dev libgomp1
  libidn11 libisl10 libitm1 liblsan0 liblzo2-2 libmpc3 libmpfr4 libpython-dev
  libpython2.7 libpython2.7-dev libquadmath0 librtmp1 libssh2-1
  libstdc++-4.9-dev libtimedate-perl libtsan0 libubsan0 linux-libc-dev lzop
  make manpages manpages-dev patch pv python-dev python2.7-dev xz-utils
0 upgraded, 56 newly installed, 0 to remove and 3 not upgraded.
Need to get 71.5 MB of archives.
After this operation, 182 MB of additional disk space will be used.
Get:1 http://httpredir.debian.org/debian/ jessie/main libidn11 amd64 1.29-1+deb8u2 [136 kB]
Get:2 http://httpredir.debian.org/debian/ jessie/main libasan1 amd64 4.9.2-10 [195 kB]
Get:3 http://httpredir.debian.org/debian/ jessie/main libatomic1 amd64 4.9.2-10 [8,992 B]
Get:4 http://httpredir.debian.org/debian/ jessie/main libcilkrts5 amd64 4.9.2-10 [40.1 kB]
Get:5 http://httpredir.debian.org/debian/ jessie/main libisl10 amd64 0.12.2-2 [440 kB]
Get:6 http://httpredir.debian.org/debian/ jessie/main libcloog-isl4 amd64 0.18.2-1+b2 [61.8 kB]
Get:7 http://httpredir.debian.org/debian/ jessie/main librtmp1 amd64 2.4+20150115.gita107cef-1 [59.8 kB]
Get:8 http://httpredir.debian.org/debian/ jessie/main libssh2-1 amd64 1.4.3-4.1+deb8u1 [125 kB]
Get:9 http://httpredir.debian.org/debian/ jessie/main libcurl3 amd64 7.38.0-4+deb8u4 [259 kB]
Get:10 http://httpredir.debian.org/debian/ jessie/main libgomp1 amd64 4.9.2-10 [37.8 kB]
Get:11 http://httpredir.debian.org/debian/ jessie/main libitm1 amd64 4.9.2-10 [29.2 kB]
Get:12 http://httpredir.debian.org/debian/ jessie/main liblsan0 amd64 4.9.2-10 [92.8 kB]
Get:13 http://httpredir.debian.org/debian/ jessie/main liblzo2-2 amd64 2.08-1.2 [54.6 kB]
Get:14 http://httpredir.debian.org/debian/ jessie/main libmpfr4 amd64 3.1.2-2 [527 kB]
Get:15 http://httpredir.debian.org/debian/ jessie/main libpython2.7 amd64 2.7.9-2+deb8u1 [1,081 kB]
Get:16 http://httpredir.debian.org/debian/ jessie/main libc-dev-bin amd64 2.19-18+deb8u6 [238 kB]
Get:17 http://httpredir.debian.org/debian/ jessie/main libc6-dev amd64 2.19-18+deb8u6 [2,002 kB]
Get:18 http://httpredir.debian.org/debian/ jessie/main libexpat1-dev amd64 2.1.0-6+deb8u3 [126 kB]
Get:19 http://httpredir.debian.org/debian/ jessie/main linux-libc-dev amd64 3.16.36-1+deb8u1 [1,034 kB]
Get:20 http://httpredir.debian.org/debian/ jessie/main libmpc3 amd64 1.0.2-1 [39.3 kB]
Get:21 http://httpredir.debian.org/debian/ jessie/main libpython2.7-dev amd64 2.7.9-2+deb8u1 [18.6 MB]
Get:22 http://httpredir.debian.org/debian/ jessie/main cpp-4.9 amd64 4.9.2-10 [5,169 kB]
Get:23 http://httpredir.debian.org/debian/ jessie/main cpp amd64 4:4.9.2-2 [17.3 kB]
Get:24 http://httpredir.debian.org/debian/ jessie/main gcc-4.9 amd64 4.9.2-10 [5,352 kB]
Get:25 http://httpredir.debian.org/debian/ jessie/main g++-4.9 amd64 4.9.2-10 [21.4 MB]
Get:26 http://httpredir.debian.org/debian/ jessie/main g++ amd64 4:4.9.2-2 [1,530 B]
Get:27 http://httpredir.debian.org/debian/ jessie/main make amd64 4.0-8.1 [349 kB]
Get:28 http://httpredir.debian.org/debian/ jessie/main libtimedate-perl all 2.3000-2 [42.2 kB]
Get:29 http://httpredir.debian.org/debian/ jessie/main build-essential amd64 11.7 [7,114 B]
Get:30 http://httpredir.debian.org/debian/ jessie/main libfakeroot amd64 1.20.2-1 [44.7 kB]
Get:31 http://httpredir.debian.org/debian/ jessie/main fakeroot amd64 1.20.2-1 [84.7 kB]
Get:32 http://httpredir.debian.org/debian/ jessie/main libalgorithm-diff-perl all 1.19.02-3 [51.7 kB]
Get:33 http://httpredir.debian.org/debian/ jessie/main libalgorithm-merge-perl all 0.08-2 [13.5 kB]
Get:34 http://httpredir.debian.org/debian/ jessie/main libquadmath0 amd64 4.9.2-10 [129 kB]
Get:35 http://httpredir.debian.org/debian/ jessie/main libfile-fcntllock-perl amd64 0.22-1+b1 [36.4 kB]
Get:36 http://httpredir.debian.org/debian/ jessie/main libtsan0 amd64 4.9.2-10 [212 kB]
Get:37 http://httpredir.debian.org/debian/ jessie/main libubsan0 amd64 4.9.2-10 [82.4 kB]
Get:38 http://httpredir.debian.org/debian/ jessie/main manpages all 3.74-1 [997 kB]
Get:39 http://httpredir.debian.org/debian/ jessie/main libpython-dev amd64 2.7.9-1 [19.6 kB]
Get:40 http://httpredir.debian.org/debian/ jessie/main patch amd64 2.7.5-1 [109 kB]
Get:41 http://httpredir.debian.org/debian/ jessie/main xz-utils amd64 5.1.1alpha+20120614-2+b3 [221 kB]
Get:42 http://httpredir.debian.org/debian/ jessie/main binutils amd64 2.25-5 [3,516 kB]
Get:43 http://httpredir.debian.org/debian/ jessie/main libgcc-4.9-dev amd64 4.9.2-10 [2,066 kB]
Get:44 http://httpredir.debian.org/debian/ jessie/main python2.7-dev amd64 2.7.9-2+deb8u1 [290 kB]
Get:45 http://httpredir.debian.org/debian/ jessie/main python-dev amd64 2.7.9-1 [1,182 B]
Get:46 http://httpredir.debian.org/debian/ jessie/main gcc amd64 4:4.9.2-2 [5,136 B]
Get:47 http://httpredir.debian.org/debian/ jessie/main libstdc++-4.9-dev amd64 4.9.2-10 [1,121 kB]
Get:48 http://httpredir.debian.org/debian/ jessie/main libdpkg-perl all 1.17.27 [1,075 kB]
Get:49 http://httpredir.debian.org/debian/ jessie/main dpkg-dev all 1.17.27 [1,548 kB]
Get:50 http://httpredir.debian.org/debian/ jessie/main ca-certificates all 20141019+deb8u1 [204 kB]
Get:51 http://httpredir.debian.org/debian/ jessie/main curl amd64 7.38.0-4+deb8u4 [200 kB]
Get:52 http://httpredir.debian.org/debian/ jessie/main daemontools amd64 1:0.76-6 [57.6 kB]
Get:53 http://httpredir.debian.org/debian/ jessie/main libalgorithm-diff-xs-perl amd64 0.04-3+b1 [12.2 kB]
Get:54 http://httpredir.debian.org/debian/ jessie/main lzop amd64 1.03-3 [44.8 kB]
Get:55 http://httpredir.debian.org/debian/ jessie/main manpages-dev all 3.74-1 [1,865 kB]
Get:56 http://httpredir.debian.org/debian/ jessie/main pv amd64 1.5.7-2 [45.4 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 71.5 MB in 6s (11.5 MB/s)
Selecting previously unselected package libidn11:amd64.
(Reading database ... 12485 files and directories currently installed.)
Preparing to unpack .../libidn11_1.29-1+deb8u2_amd64.deb ...
Unpacking libidn11:amd64 (1.29-1+deb8u2) ...
Selecting previously unselected package libasan1:amd64.
Preparing to unpack .../libasan1_4.9.2-10_amd64.deb ...
Unpacking libasan1:amd64 (4.9.2-10) ...
Selecting previously unselected package libatomic1:amd64.
Preparing to unpack .../libatomic1_4.9.2-10_amd64.deb ...
Unpacking libatomic1:amd64 (4.9.2-10) ...
Selecting previously unselected package libcilkrts5:amd64.
Preparing to unpack .../libcilkrts5_4.9.2-10_amd64.deb ...
Unpacking libcilkrts5:amd64 (4.9.2-10) ...
Selecting previously unselected package libisl10:amd64.
Preparing to unpack .../libisl10_0.12.2-2_amd64.deb ...
Unpacking libisl10:amd64 (0.12.2-2) ...
Selecting previously unselected package libcloog-isl4:amd64.
Preparing to unpack .../libcloog-isl4_0.18.2-1+b2_amd64.deb ...
Unpacking libcloog-isl4:amd64 (0.18.2-1+b2) ...
Selecting previously unselected package librtmp1:amd64.
Preparing to unpack .../librtmp1_2.4+20150115.gita107cef-1_amd64.deb ...
Unpacking librtmp1:amd64 (2.4+20150115.gita107cef-1) ...
Selecting previously unselected package libssh2-1:amd64.
Preparing to unpack .../libssh2-1_1.4.3-4.1+deb8u1_amd64.deb ...
Unpacking libssh2-1:amd64 (1.4.3-4.1+deb8u1) ...
Selecting previously unselected package libcurl3:amd64.
Preparing to unpack .../libcurl3_7.38.0-4+deb8u4_amd64.deb ...
Unpacking libcurl3:amd64 (7.38.0-4+deb8u4) ...
Selecting previously unselected package libgomp1:amd64.
Preparing to unpack .../libgomp1_4.9.2-10_amd64.deb ...
Unpacking libgomp1:amd64 (4.9.2-10) ...
Selecting previously unselected package libitm1:amd64.
Preparing to unpack .../libitm1_4.9.2-10_amd64.deb ...
Unpacking libitm1:amd64 (4.9.2-10) ...
Selecting previously unselected package liblsan0:amd64.
Preparing to unpack .../liblsan0_4.9.2-10_amd64.deb ...
Unpacking liblsan0:amd64 (4.9.2-10) ...
Selecting previously unselected package liblzo2-2:amd64.
Preparing to unpack .../liblzo2-2_2.08-1.2_amd64.deb ...
Unpacking liblzo2-2:amd64 (2.08-1.2) ...
Selecting previously unselected package libmpfr4:amd64.
Preparing to unpack .../libmpfr4_3.1.2-2_amd64.deb ...
Unpacking libmpfr4:amd64 (3.1.2-2) ...
Selecting previously unselected package libpython2.7:amd64.
Preparing to unpack .../libpython2.7_2.7.9-2+deb8u1_amd64.deb ...
Unpacking libpython2.7:amd64 (2.7.9-2+deb8u1) ...
Selecting previously unselected package libc-dev-bin.
Preparing to unpack .../libc-dev-bin_2.19-18+deb8u6_amd64.deb ...
Unpacking libc-dev-bin (2.19-18+deb8u6) ...
Selecting previously unselected package linux-libc-dev:amd64.
Preparing to unpack .../linux-libc-dev_3.16.36-1+deb8u1_amd64.deb ...
Unpacking linux-libc-dev:amd64 (3.16.36-1+deb8u1) ...
Selecting previously unselected package libc6-dev:amd64.
Preparing to unpack .../libc6-dev_2.19-18+deb8u6_amd64.deb ...
Unpacking libc6-dev:amd64 (2.19-18+deb8u6) ...
Selecting previously unselected package libexpat1-dev:amd64.
Preparing to unpack .../libexpat1-dev_2.1.0-6+deb8u3_amd64.deb ...
Unpacking libexpat1-dev:amd64 (2.1.0-6+deb8u3) ...
Selecting previously unselected package libpython2.7-dev:amd64.
Preparing to unpack .../libpython2.7-dev_2.7.9-2+deb8u1_amd64.deb ...
Unpacking libpython2.7-dev:amd64 (2.7.9-2+deb8u1) ...
Selecting previously unselected package libquadmath0:amd64.
Preparing to unpack .../libquadmath0_4.9.2-10_amd64.deb ...
Unpacking libquadmath0:amd64 (4.9.2-10) ...
Selecting previously unselected package libtsan0:amd64.
Preparing to unpack .../libtsan0_4.9.2-10_amd64.deb ...
Unpacking libtsan0:amd64 (4.9.2-10) ...
Selecting previously unselected package libubsan0:amd64.
Preparing to unpack .../libubsan0_4.9.2-10_amd64.deb ...
Unpacking libubsan0:amd64 (4.9.2-10) ...
Selecting previously unselected package libmpc3:amd64.
Preparing to unpack .../libmpc3_1.0.2-1_amd64.deb ...
Unpacking libmpc3:amd64 (1.0.2-1) ...
Selecting previously unselected package manpages.
Preparing to unpack .../manpages_3.74-1_all.deb ...
Unpacking manpages (3.74-1) ...
Selecting previously unselected package patch.
Preparing to unpack .../patch_2.7.5-1_amd64.deb ...
Unpacking patch (2.7.5-1) ...
Selecting previously unselected package xz-utils.
Preparing to unpack .../xz-utils_5.1.1alpha+20120614-2+b3_amd64.deb ...
Unpacking xz-utils (5.1.1alpha+20120614-2+b3) ...
Selecting previously unselected package binutils.
Preparing to unpack .../binutils_2.25-5_amd64.deb ...
Unpacking binutils (2.25-5) ...
Selecting previously unselected package cpp-4.9.
Preparing to unpack .../cpp-4.9_4.9.2-10_amd64.deb ...
Unpacking cpp-4.9 (4.9.2-10) ...
Selecting previously unselected package cpp.
Preparing to unpack .../cpp_4%3a4.9.2-2_amd64.deb ...
Unpacking cpp (4:4.9.2-2) ...
Selecting previously unselected package libgcc-4.9-dev:amd64.
Preparing to unpack .../libgcc-4.9-dev_4.9.2-10_amd64.deb ...
Unpacking libgcc-4.9-dev:amd64 (4.9.2-10) ...
Selecting previously unselected package gcc-4.9.
Preparing to unpack .../gcc-4.9_4.9.2-10_amd64.deb ...
Unpacking gcc-4.9 (4.9.2-10) ...
Selecting previously unselected package gcc.
Preparing to unpack .../gcc_4%3a4.9.2-2_amd64.deb ...
Unpacking gcc (4:4.9.2-2) ...
Selecting previously unselected package libstdc++-4.9-dev:amd64.
Preparing to unpack .../libstdc++-4.9-dev_4.9.2-10_amd64.deb ...
Unpacking libstdc++-4.9-dev:amd64 (4.9.2-10) ...
Selecting previously unselected package g++-4.9.
Preparing to unpack .../g++-4.9_4.9.2-10_amd64.deb ...
Unpacking g++-4.9 (4.9.2-10) ...
Selecting previously unselected package g++.
Preparing to unpack .../g++_4%3a4.9.2-2_amd64.deb ...
Unpacking g++ (4:4.9.2-2) ...
Selecting previously unselected package make.
Preparing to unpack .../make_4.0-8.1_amd64.deb ...
Unpacking make (4.0-8.1) ...
Selecting previously unselected package libtimedate-perl.
Preparing to unpack .../libtimedate-perl_2.3000-2_all.deb ...
Unpacking libtimedate-perl (2.3000-2) ...
Selecting previously unselected package libdpkg-perl.
Preparing to unpack .../libdpkg-perl_1.17.27_all.deb ...
Unpacking libdpkg-perl (1.17.27) ...
Selecting previously unselected package dpkg-dev.
Preparing to unpack .../dpkg-dev_1.17.27_all.deb ...
Unpacking dpkg-dev (1.17.27) ...
Selecting previously unselected package build-essential.
Preparing to unpack .../build-essential_11.7_amd64.deb ...
Unpacking build-essential (11.7) ...
Selecting previously unselected package ca-certificates.
Preparing to unpack .../ca-certificates_20141019+deb8u1_all.deb ...
Unpacking ca-certificates (20141019+deb8u1) ...
Selecting previously unselected package curl.
Preparing to unpack .../curl_7.38.0-4+deb8u4_amd64.deb ...
Unpacking curl (7.38.0-4+deb8u4) ...
Selecting previously unselected package daemontools.
Preparing to unpack .../daemontools_1%3a0.76-6_amd64.deb ...
Unpacking daemontools (1:0.76-6) ...
Selecting previously unselected package libfakeroot:amd64.
Preparing to unpack .../libfakeroot_1.20.2-1_amd64.deb ...
Unpacking libfakeroot:amd64 (1.20.2-1) ...
Selecting previously unselected package fakeroot.
Preparing to unpack .../fakeroot_1.20.2-1_amd64.deb ...
Unpacking fakeroot (1.20.2-1) ...
Selecting previously unselected package libalgorithm-diff-perl.
Preparing to unpack .../libalgorithm-diff-perl_1.19.02-3_all.deb ...
Unpacking libalgorithm-diff-perl (1.19.02-3) ...
Selecting previously unselected package libalgorithm-diff-xs-perl.
Preparing to unpack .../libalgorithm-diff-xs-perl_0.04-3+b1_amd64.deb ...
Unpacking libalgorithm-diff-xs-perl (0.04-3+b1) ...
Selecting previously unselected package libalgorithm-merge-perl.
Preparing to unpack .../libalgorithm-merge-perl_0.08-2_all.deb ...
Unpacking libalgorithm-merge-perl (0.08-2) ...
Selecting previously unselected package libfile-fcntllock-perl.
Preparing to unpack .../libfile-fcntllock-perl_0.22-1+b1_amd64.deb ...
Unpacking libfile-fcntllock-perl (0.22-1+b1) ...
Selecting previously unselected package libpython-dev:amd64.
Preparing to unpack .../libpython-dev_2.7.9-1_amd64.deb ...
Unpacking libpython-dev:amd64 (2.7.9-1) ...
Selecting previously unselected package lzop.
Preparing to unpack .../archives/lzop_1.03-3_amd64.deb ...
Unpacking lzop (1.03-3) ...
Selecting previously unselected package manpages-dev.
Preparing to unpack .../manpages-dev_3.74-1_all.deb ...
Unpacking manpages-dev (3.74-1) ...
Selecting previously unselected package pv.
Preparing to unpack .../archives/pv_1.5.7-2_amd64.deb ...
Unpacking pv (1.5.7-2) ...
Selecting previously unselected package python2.7-dev.
Preparing to unpack .../python2.7-dev_2.7.9-2+deb8u1_amd64.deb ...
Unpacking python2.7-dev (2.7.9-2+deb8u1) ...
Selecting previously unselected package python-dev.
Preparing to unpack .../python-dev_2.7.9-1_amd64.deb ...
Unpacking python-dev (2.7.9-1) ...
Setting up libidn11:amd64 (1.29-1+deb8u2) ...
Setting up libasan1:amd64 (4.9.2-10) ...
Setting up libatomic1:amd64 (4.9.2-10) ...
Setting up libcilkrts5:amd64 (4.9.2-10) ...
Setting up libisl10:amd64 (0.12.2-2) ...
Setting up libcloog-isl4:amd64 (0.18.2-1+b2) ...
Setting up librtmp1:amd64 (2.4+20150115.gita107cef-1) ...
Setting up libssh2-1:amd64 (1.4.3-4.1+deb8u1) ...
Setting up libcurl3:amd64 (7.38.0-4+deb8u4) ...
Setting up libgomp1:amd64 (4.9.2-10) ...
Setting up libitm1:amd64 (4.9.2-10) ...
Setting up liblsan0:amd64 (4.9.2-10) ...
Setting up liblzo2-2:amd64 (2.08-1.2) ...
Setting up libmpfr4:amd64 (3.1.2-2) ...
Setting up libpython2.7:amd64 (2.7.9-2+deb8u1) ...
Setting up libc-dev-bin (2.19-18+deb8u6) ...
Setting up linux-libc-dev:amd64 (3.16.36-1+deb8u1) ...
Setting up libc6-dev:amd64 (2.19-18+deb8u6) ...
Setting up libexpat1-dev:amd64 (2.1.0-6+deb8u3) ...
Setting up libpython2.7-dev:amd64 (2.7.9-2+deb8u1) ...
Setting up libquadmath0:amd64 (4.9.2-10) ...
Setting up libtsan0:amd64 (4.9.2-10) ...
Setting up libubsan0:amd64 (4.9.2-10) ...
Setting up libmpc3:amd64 (1.0.2-1) ...
Setting up manpages (3.74-1) ...
Setting up patch (2.7.5-1) ...
Setting up xz-utils (5.1.1alpha+20120614-2+b3) ...
update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode
Setting up binutils (2.25-5) ...
Setting up cpp-4.9 (4.9.2-10) ...
Setting up cpp (4:4.9.2-2) ...
Setting up libgcc-4.9-dev:amd64 (4.9.2-10) ...
Setting up gcc-4.9 (4.9.2-10) ...
Setting up gcc (4:4.9.2-2) ...
Setting up libstdc++-4.9-dev:amd64 (4.9.2-10) ...
Setting up g++-4.9 (4.9.2-10) ...
Setting up g++ (4:4.9.2-2) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Setting up make (4.0-8.1) ...
Setting up libtimedate-perl (2.3000-2) ...
Setting up libdpkg-perl (1.17.27) ...
Setting up dpkg-dev (1.17.27) ...
Setting up build-essential (11.7) ...
Setting up ca-certificates (20141019+deb8u1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Setting up curl (7.38.0-4+deb8u4) ...
Setting up daemontools (1:0.76-6) ...
Setting up libfakeroot:amd64 (1.20.2-1) ...
Setting up fakeroot (1.20.2-1) ...
update-alternatives: using /usr/bin/fakeroot-sysv to provide /usr/bin/fakeroot (fakeroot) in auto mode
Setting up libalgorithm-diff-perl (1.19.02-3) ...
Setting up libalgorithm-diff-xs-perl (0.04-3+b1) ...
Setting up libalgorithm-merge-perl (0.08-2) ...
Setting up libfile-fcntllock-perl (0.22-1+b1) ...
Setting up libpython-dev:amd64 (2.7.9-1) ...
Setting up lzop (1.03-3) ...
Setting up manpages-dev (3.74-1) ...
Setting up pv (1.5.7-2) ...
Setting up python2.7-dev (2.7.9-2+deb8u1) ...
Setting up python-dev (2.7.9-1) ...
Processing triggers for libc-bin (2.19-18+deb8u6) ...
Processing triggers for ca-certificates (20141019+deb8u1) ...
Updating certificates in /etc/ssl/certs... 174 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
Collecting pip
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)
Collecting setuptools
  Downloading setuptools-28.2.0-py2.py3-none-any.whl (467kB)
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-8.1.2 setuptools-28.2.0 wheel-0.29.0
Collecting wal-e
  Downloading wal-e-1.0.0.tar.gz (88kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-DI97ai/wal-e/setup.py", line 19, in <module>
        raise RuntimeError('Python versions < 3.4 are not supported.')
    RuntimeError: Python versions < 3.4 are not supported.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-DI97ai/wal-e/
ERROR: Service 'db' failed to build: The command '/bin/sh -c apt-get update     && apt-get install -y python-dev lzop pv daemontools curl build-essential     && curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | python     && pip install wal-e     && apt-get remove -y build-essential python-dev     && apt-get autoremove -y     && apt-get clean     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 1
```

I've tried on both master and 3.4.0 tag. My host is on Ubuntu 16.04 and I've got other working containers on this host.
Any idea ?

**Comment by npcode** [comment]
It seems that the latest wale depends python 3.4. I think we may specify the older version for wale...

/cc @xcompass

**Comment by Joris-van-der-Wel** [comment]
Here's the change that caused this: https://github.com/wal-e/wal-e/commit/1e5584488a9a5ae55693785e7d4132f7bc34cb5e#diff-2eeaed663bd0d25b7e608891384b7298R18

Here's the workaround that I used:
```diff
diff --git a/db/Dockerfile b/db/Dockerfile
index 248b974..c35098d 100644
--- a/db/Dockerfile
+++ b/db/Dockerfile
@@ -3,7 +3,7 @@ FROM postgres:9.4
 RUN apt-get update \
     && apt-get install -y python-dev lzop pv daemontools curl build-essential \
     && curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | python \
-    && pip install wal-e \
+    && pip install 'wal-e<1.0.0' \
     && apt-get remove -y build-essential python-dev \
     && apt-get autoremove -y \
     && apt-get clean \
```

**Comment by remialvado** [comment]
Thanks ! It work fine now.  I've send a PR to fix it on master

**Comment by somuraijoe** [comment]
a new version should be launched as I used the tutorial that takes from enterprise branch and I did same modification as above

**Comment by paladini** [comment]
Same issue here! Please, accept the pull request ASAP.

**Comment by npcode** [comment]
@paladini The pull request was already merged into master branch at 3cb431a35cc3f6e39c9156a3e29a86af8bb7000e. But images in dockerhub are not updated yet. Are you using them?

@it33 Could you please merge or cherry-pick https://github.com/mattermost/mattermost-docker/pull/54 into `enterprise` branch for @somuraijoe?

**Comment by it33** [comment]
I deleted the `enterprise` branch and created a new `team-and-enterprise` branch off of master and updated the [Docker tutorial instructions](https://github.com/mattermost/docs/pull/598/files). 

Previously the Enterprise Edition could only be used with subscription, but we created a new license that lets the [Enterprise Edition be used for free](https://docs.mattermost.com/administration/upgrade.html#version-archive) with the same features as Team Edition, and it includes the ability to upgrade into full Enterprise Edition with a license key.

We had a lot of help requests of people trying to uninstall Team Edition in order to unlock Enterprise Edition, so we decided to make it easier by offering the free mode in Enterprise Edition so they don't have to uninstall and re-install to upgrade. 

Also, if they choose to downgrade, it's really easy now because all you do is remove the license key and you can keep using the software for free and don't have to uninstall and reinstall

**Comment by paladini** [comment]
@it33 Yesterday I've installed Mattermost using enterprise branch (I'll use free version). Should I uninstall it and reinstall using team-and-enterprise branch? There's a difference between "enterprise" and "team-and-enterprise" branch right now?

**Comment by it33** [comment]
@paladini the new `team-and-enterprise` and old `enterprise` branch should have the same binary, it's just `team-and-enterprise` has the latest fixes from `master`

Sorry for the confusion, hopefully this new method is easier,

**Comment by paladini** [comment]
Ah, okay! Now I get it, thanks for the answer. And yes, I do think this new method is better too.

**Comment by xcompass** [comment]
Since PR #54 is merged. I'm closing this issue now.
